### ISSUE TITLE
[QUESTION] What all details do we want to show on the dashboard?

### ISSUE THREAD

**Issue by apoorvaeternity** [weecology/retrieverdash#2]
@ethanwhite 
What all details do we want to show on the dashboard?
Is the dashboard for maintainers as well as users going to be the same or different?

**Comment by henrykironde** [comment]
We are looking for dashboard features that will tell us the installation status(passing or has errors), the last known hash number of dataset when it was installing fine and possible log summary of what changed of a diff.

We are going to have something like this 


| Dataset        | Installation status          | Data modified date | Md5 hash          | 
| ------------- |:-------------:| -----:|-----:|
| Iris      | :white_check_mark: |  | b33bdefd587281bdf458bcd0d442a866b52c8ed1 |
| Portal      | :heavy_exclamation_mark:      |   02/18/2018/....|
| Airports | :heavy_exclamation_mark:   |    01/03/2017/.... |b33bdefd587281bdf458bcd0d442a866b52c8ed1 |

or 

| Dataset        | Installation status          | Data modified date | Md5 hash          | Diff
| ------------- |:-------------:| -----:|-----:|-----:|
| Iris      | :white_check_mark: |  | b33bdefd587281bdf458bcd0d442a866b52c8ed1 | [a link to the error log or diff](https://github.com/weecology/retrieverdash/issues/2)
| Portal      | :heavy_exclamation_mark:      |   02/18/2018/.... |
| Airports | :heavy_exclamation_mark:   |    01/03/2017/.... |

We can have the date when the dashboard was last modified or when the script was last run at the top of the dashboard.

Overall we need to know

```python
if the datasets install fine with no errors:
```

However,

```python
   if a dataset installs fine or not:
        if the hash is different from the last time it was installing fine + with a know hash:
            then we need to provide some message or diff log 
```

**Comment by apoorvaeternity** [comment]
@henrykironde Okay. I will create a mockup for it.

**Comment by ethanwhite** [comment]
:+1: to @henrykironde's plan

**Comment by apoorvaeternity** [comment]
@henrykironde @ethanwhite  Something just like this.![mockup](https://user-images.githubusercontent.com/21103831/36688651-24f36da4-1b53-11e8-857a-a2f13d498054.png)

**Comment by henrykironde** [comment]
Looks like a good and promising start.
