### ISSUE TITLE
Master branch pointed instead of Main

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retrieverdash#37]
After cloning the Retriever dash and following the README. <br>
When I run the command ` pip install -r requirements.txt` <br> it is giving me error as <br>
`ERROR: Command errored out with exit status 1: git checkout -q master Check the logs for full command output.`.

I am attaching a Screenshot for your reference: <br>
![Image](https://i.ibb.co/1rvCNMF/Screenshot-2021-03-16-012719.png).
@henrykironde  Could you look into this matter.
Thanks.

**Comment by henrykironde** [comment]
@Mohitkumar6122, thank you for reporting this. A PR that will solve this issue has been submitted.
