### ISSUE TITLE
Error in installing retrieverdash in windows

### ISSUE THREAD

**Issue by Mohitkumar6122** [weecology/retrieverdash#43]
After using `pip install -r requirements.txt -U`  on **WINDOWS** I am getting the following output on my terminal.
```
C:\Users\Hacker\retrieverdash\retrieverdash>pip install -r requirements.txT -U
Collecting git+https://www.github.com/weecology/retriever@main (from -r requirements.txT (line 25))
  Cloning https://www.github.com/weecology/retriever (to revision main) to c:\users\hacker\appdata\local\temp\pip-req-build-uas3h4ot
  Running command git clone -q https://www.github.com/weecology/retriever 'C:\Users\Hacker\AppData\Local\Temp\pip-req-build-uas3h4ot'
  error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
  error: 6594 bytes of body are still expected
  fatal: the remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
WARNING: Discarding git+https://www.github.com/weecology/retriever@main. Command errored out with exit status 128: git clone -q https://www.github.com/weecology/retriever 'C:\Users\Hacker\AppData\Local\Temp\pip-req-build-uas3h4ot' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://www.github.com/weecology/retriever 'C:\Users\Hacker\AppData\Local\Temp\pip-req-build-uas3h4ot' Check the logs for full command output.
```
Any ideas how this is happening ? 
After running it again I am getting this error at `h5py` installation 
```Building wheels for collected packages: h5py
  Building wheel for h5py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
```

**Comment by Mohitkumar6122** [comment]
its the error i am getting and I cant find the solution on the internet.
@henrykironde Any views on it ?

**Comment by ethanwhite** [comment]
This is working fine for me at the moment (Ubuntu 20.10; Python 3.9.2)

```sh
git clone https://github.com/weecology/retrieverdash.git
cd retrieverdash/retrieverdash/
pip install -r requirements.txt
```

The initial error looks like maybe a failed download from a git repo, which is probably why when you tried it again you got a different error.

The second error is a failed dependency install. When I tested the `h5py` wheel had to be built from source, which could introduce some system dependence issues. My recommendation would be to install it using `conda` and then retry the install.

```sh
conda install h5py
pip install -r requirements.txt
```

**Comment by Mohitkumar6122** [comment]
> This is working fine for me at the moment (Ubuntu 20.10; Python 3.9.2)
> 
> ```shell
> git clone https://github.com/weecology/retrieverdash.git
> cd retrieverdash/retrieverdash/
> pip install -r requirements.txt
> ```
> 
> The initial error looks like maybe a failed download from a git repo, which is probably why when you tried it again you got a different error.
> 
> The second error is a failed dependency install. When I tested the `h5py` wheel had to be built from source, which could introduce some system dependence issues. My recommendation would be to install it using `conda` and then retry the install.
> 
> ```shell
> conda install h5py
> pip install -r requirements.txt
> ```

Sure I will try this one out @ethanwhite.
